### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'dumps' "

### ISSUE THREAD

**Issue by a-gavrilova** [HelmchenLabSoftware/CaImAn_DendriteAnalysis#1]
Hi! I use CaImAn algorithm for dendritic analysis. I ran the motion correction code in Visual Studio as python file, everything was fine until setting up clusters: I received an error: "AttributeError: 'NoneType' object has no attribute 'dumps' ". However, when I run the same part of a code in Jupyter notebook, no error appears. 
Could you please suggest, why this error appears in .py file and how can I resolve this problem? Thank you!

**Comment by hluetck** [comment]
Hello, could you please provide some more details about the code that you are trying to run? Which branch of the repository are you using and what is the code that is not working in VS?

**Comment by a-gavrilova** [comment]
Hi! Thank you for your reply!.
I was trying to run this code: https://github.com/HelmchenLabSoftware/CaImAn_DendriteAnalysis/blob/master/01_Preprocess_MotionCorrect.ipynb, with some adjustments. In VS doesn't work the part with cropping TIF files, the error is that "is_movie" is not defined in this line:

tiff_files_crop = [x.replace('.tif','_crop.tif') for ix, x in enumerate(tiff_files) if is_movie[ix]]

What is this "is_movie" mean? Is it necessary in general to crop the video and how not cropping may affect the motion correction process?

Sorry for stupid questions, I'm not very professional in programming and only recently started to work with calcium analysis codes =(

Thank you for help!

**Comment by a-gavrilova** [comment]
Hi!
I was trying to run this code with some adjustments: https://github.com/HelmchenLabSoftware/CaImAn_DendriteAnalysis/blob/master/01_Preprocess_MotionCorrect.ipynb

I haven't run all the code, followed step by step and at the cluster setting step I received this error:

_pickle.PicklingError: Can't pickle <function cropTif at 0x0000024A9D6BD5A0>: attribute lookup cropTif on __main__ failed
Exception ignored in: <function Pool.__del__ at 0x0000024A93062E60>
Traceback (most recent call last):
  File "C:\Users\melod\anaconda3\envs\caiman\lib\multiprocessing\pool.py", line 271, in __del__
  File "C:\Users\melod\anaconda3\envs\caiman\lib\multiprocessing\queues.py", line 371, in put
AttributeError: 'NoneType' object has no attribute 'dumps'

So the problem is not with the code itself, but with maybe directory or smth else.

**Comment by a-gavrilova** [comment]
Sorry for stupid questions, I'm new in programming and especially in calcium data analysis =/

**Comment by hluetck** [comment]
I think the issue here is that the function cropTif is defined in the Jupyter notebook. If you run in a non-interactive environment, the functions need to be imported explicitly. This is actually how it is done on the [caiman_latest](https://github.com/HelmchenLabSoftware/CaImAn_DendriteAnalysis/tree/caiman_latest) branch. Please have a look at [utils.py](https://github.com/HelmchenLabSoftware/CaImAn_DendriteAnalysis/blob/caiman_latest/utils.py) which is then imported in the [notebook](https://github.com/HelmchenLabSoftware/CaImAn_DendriteAnalysis/blob/caiman_latest/01_Preprocess_MC_3D.ipynb).

**Comment by a-gavrilova** [comment]
Okay, I will have a look at that code!
